version: "3"
services:
  mongodb:
    container_name: mongodb
    image: mongo
    networks:
      - dev
    ports:
      - 27017:27017
    volumes:
      - db-data-dev:/data/db:rw
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmindev
      - MONGO_INITDB_ROOT_PASSWORD=mongoadmindev1234
      - MONGO_INITDB_DATABASE=denimintsaev
    restart: unless-stopped
  mongo-express:
    container_name: mongoexpress
    image: mongo-express
    networks:
      - dev
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongoadmindev
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mongoadmindev1234
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
    restart: unless-stopped
networks:
  dev:
volumes:
  db-data-dev:
    driver: local
