version: "3"
services:
  mongo:
    container_name: dm-mongo
    image: mongo
    networks:
      - dm-dev
    ports:
      - 127.0.0.1:27017:27017
    volumes:
      - dev-db-data:/data/db:rw
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmindev
      - MONGO_INITDB_ROOT_PASSWORD=mongoadmindev123
      - MONGO_INITDB_DATABASE=denimintsaev
    restart: unless-stopped
  mongo-express:
    container_name: dm-mongo-express
    image: mongo-express
    networks:
      - dm-dev
    ports:
      - 127.0.0.1:8080:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=dm-mongo
      - ME_CONFIG_MONGODB_AUTH_USERNAME=mongoadmindev
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=mongoadmindev123
    depends_on:
      - mongo
    restart: unless-stopped
networks:
  dm-dev:
volumes:
  dev-db-data:
    # Tells docker to create the storage for the volume on the local file system
    driver: local
