version: "3"
services:
  mongo:
    container_name: dev-mongo
    image: mongo
    networks:
      - dev
    ports:
      - 27017:27017
    volumes:
      - db-data-dev:/data/db:rw
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmindev
      - MONGO_INITDB_ROOT_PASSWORD=mongoadmindev123
      - MONGO_INITDB_DATABASE=denimintsaev
    restart: unless-stopped
  mongo-express:
    container_name: dev-mongo-express
    image: mongo-express
    networks:
      - dev
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=dev-mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=mongoadmindev
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=mongoadmindev123
      - ME_CONFIG_BASICAUTH_USERNAME=userdev
      - ME_CONFIG_BASICAUTH_PASSWORD=passworddev
    depends_on:
      - mongo
    restart: unless-stopped
networks:
  dev:
volumes:
  db-data-dev:
    driver: local
