version: '3'
services:
  mongo:
    container_name: dm-mongo
    image: mongo
    networks:
      - denimintsaev
    ports:
      # Map host's port (left) on localhost to container's port (right)
      - '127.0.0.1:27017:27017'
    volumes:
      - db-data:/data/db:rw
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ADMIN_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ADMIN_PASSWORD}
      - MONGO_INITDB_DATABASE=denimintsaev
    restart: always
  dm-server:
    container_name: denimintsaev
    image: denimint/denimintsaev.com
    build: .
    networks:
      - denimintsaev
    ports:
      - 127.0.0.1:3000:3000
    environment:
      - MONGODB_URI='mongodb://${MONGO_ADMIN_USERNAME}:${MONGO_ADMIN_PASSWORD}@dm-mongo:27017'
    depends_on:
      - mongo
    restart: always
networks:
  denimintsaev:
volumes:
  db-data:
    # Tells docker to create the storage for the volume on the local file system
    driver: local
