/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './components/**/*.{js,vue,ts}',
    './layouts/**/*.vue',
    './pages/**/*.vue',
    './plugins/**/*.{js,ts}',
    './nuxt.config.{js,ts}',
  ],
  theme: {
    extend: {
      colors: {
        mygray: {
          50: '#eeeeee',
          100: '#dddddd',
          200: '#cccccc',
          300: '#bbbbbb',
          400: '#a9a9a9',
          500: '#959595',
          600: '#7c7c7c',
          700: '#5c5c5c',
          800: '#414141',
          900: '#222222',
        },
      },
    },
  },
  // variants: {
  //   extend: {
  //     backgroundColor: ['active'],
  //   },
  // },
  css: ['~/assets/css/main.css', '~/assets/css/kanjiSorter.css'],
  plugins: [],
  purge: {
    enabled: true,
    options: {
      safelist: [
        'w-36',
        'w-40',
        'max-w-screen-sm',
        'max-w-screen-md',
        'max-w-screen-lg',
        'py-1',
        'py-2',
        'py-3',
        'py-4',
        'py-5',
        'py-6',
        'py-8',
        'md:py-1',
        'md:py-2',
        'md:py-3',
        'md:py-4',
        'md:py-5',
        'md:py-6',
        'text-xl',
        'text-2xl',
        'text-3xl',
        'text-4xl',
        'text-5xl',
        'md:text-2xl',
        'md:text-3xl',
        'md:text-4xl',
        'md:text-5xl',
        'text-black',
        'text-white',
      ],
    },
  },
};
